name: backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  postgres: ^2.4.6
  postgresql2: ^1.0.3
  shelf: ^1.3.2
  shelf_modular: ^2.0.1
  shelf_router: ^1.1.3
